
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action Action11;

	private global::Gtk.Action HTMLAction;

	private global::Gtk.Action Action2;

	private global::Gtk.Action AboutAuthorAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label label1;

	private global::Gtk.ComboBox comboboxTitle;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label2;

	private global::Gtk.ComboBox comboboxAuthor;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label label3;

	private global::Gtk.ComboBox comboboxGenre;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label4;

	private global::Gtk.ComboBox comboboxLanguage;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label5;

	private global::Gtk.SpinButton spinbuttonDateFrom;

	private global::Gtk.Label label7;

	private global::Gtk.SpinButton spinbuttonDateTo;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label6;

	private global::Gtk.SpinButton spinbuttonPagesFrom;

	private global::Gtk.Label label8;

	private global::Gtk.SpinButton spinbuttonPagesTo;

	private global::Gtk.HBox hbox2;

	private global::Gtk.RadioButton radiobuttonLINQ;

	private global::Gtk.RadioButton radiobuttonSAX;

	private global::Gtk.RadioButton radiobuttonDOM;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Button buttonSearch;

	private global::Gtk.Button buttonClear;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.Action11 = new global::Gtk.Action("Action11", global::Mono.Unix.Catalog.GetString("Файл"), null, null);
		this.Action11.ShortLabel = global::Mono.Unix.Catalog.GetString("Файл");
		w1.Add(this.Action11, null);
		this.HTMLAction = new global::Gtk.Action("HTMLAction", global::Mono.Unix.Catalog.GetString("Конвертувати в HTML"), null, null);
		this.HTMLAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Конвертувати в HTML");
		w1.Add(this.HTMLAction, null);
		this.Action2 = new global::Gtk.Action("Action2", global::Mono.Unix.Catalog.GetString("Інфо"), null, null);
		this.Action2.ShortLabel = global::Mono.Unix.Catalog.GetString("Інфо");
		w1.Add(this.Action2, null);
		this.AboutAuthorAction = new global::Gtk.Action("AboutAuthorAction", global::Mono.Unix.Catalog.GetString("Про автора"), null, null);
		this.AboutAuthorAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Про автора");
		w1.Add(this.AboutAuthorAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu name=\'Action11\' action=\'Action11\'><menuitem na" +
				"me=\'HTMLAction\' action=\'HTMLAction\'/></menu><menu name=\'Action2\' action=\'Action2" +
				"\'><menuitem name=\'AboutAuthorAction\' action=\'AboutAuthorAction\'/></menu></menuba" +
				"r></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Назва");
		this.hbox8.Add(this.label1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(28));
		// Container child hbox8.Gtk.Box+BoxChild
		this.comboboxTitle = global::Gtk.ComboBox.NewText();
		this.comboboxTitle.Name = "comboboxTitle";
		this.hbox8.Add(this.comboboxTitle);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.comboboxTitle]));
		w4.Position = 1;
		this.vbox2.Add(this.hbox8);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox8]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Ім\'я автора");
		this.hbox7.Add(this.label2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		w6.Padding = ((uint)(13));
		// Container child hbox7.Gtk.Box+BoxChild
		this.comboboxAuthor = global::Gtk.ComboBox.NewText();
		this.comboboxAuthor.Name = "comboboxAuthor";
		this.hbox7.Add(this.comboboxAuthor);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxAuthor]));
		w7.Position = 1;
		this.vbox2.Add(this.hbox7);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox7]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Жанр");
		this.hbox6.Add(this.label3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(30));
		// Container child hbox6.Gtk.Box+BoxChild
		this.comboboxGenre = global::Gtk.ComboBox.NewText();
		this.comboboxGenre.Name = "comboboxGenre";
		this.hbox6.Add(this.comboboxGenre);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.comboboxGenre]));
		w10.Position = 1;
		this.vbox2.Add(this.hbox6);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox6]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Мова оригіналу");
		this.hbox5.Add(this.label4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.comboboxLanguage = global::Gtk.ComboBox.NewText();
		this.comboboxLanguage.Name = "comboboxLanguage";
		this.hbox5.Add(this.comboboxLanguage);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.comboboxLanguage]));
		w13.Position = 1;
		this.vbox2.Add(this.hbox5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Дата написання");
		this.hbox4.Add(this.label5);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label5]));
		w15.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.spinbuttonDateFrom = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbuttonDateFrom.CanFocus = true;
		this.spinbuttonDateFrom.Name = "spinbuttonDateFrom";
		this.spinbuttonDateFrom.Adjustment.PageIncrement = 10D;
		this.spinbuttonDateFrom.ClimbRate = 1D;
		this.spinbuttonDateFrom.Numeric = true;
		this.hbox4.Add(this.spinbuttonDateFrom);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.spinbuttonDateFrom]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("-");
		this.hbox4.Add(this.label7);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label7]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.spinbuttonDateTo = new global::Gtk.SpinButton(0D, 2020D, 1D);
		this.spinbuttonDateTo.CanFocus = true;
		this.spinbuttonDateTo.Name = "spinbuttonDateTo";
		this.spinbuttonDateTo.Adjustment.PageIncrement = 10D;
		this.spinbuttonDateTo.ClimbRate = 1D;
		this.spinbuttonDateTo.Numeric = true;
		this.spinbuttonDateTo.Value = 2020D;
		this.hbox4.Add(this.spinbuttonDateTo);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.spinbuttonDateTo]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Кількість сторінок");
		this.hbox3.Add(this.label6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label6]));
		w20.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.spinbuttonPagesFrom = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbuttonPagesFrom.CanFocus = true;
		this.spinbuttonPagesFrom.Name = "spinbuttonPagesFrom";
		this.spinbuttonPagesFrom.Adjustment.PageIncrement = 10D;
		this.spinbuttonPagesFrom.ClimbRate = 1D;
		this.spinbuttonPagesFrom.Numeric = true;
		this.hbox3.Add(this.spinbuttonPagesFrom);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spinbuttonPagesFrom]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("-");
		this.hbox3.Add(this.label8);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label8]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.spinbuttonPagesTo = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbuttonPagesTo.CanFocus = true;
		this.spinbuttonPagesTo.Name = "spinbuttonPagesTo";
		this.spinbuttonPagesTo.Adjustment.PageIncrement = 10D;
		this.spinbuttonPagesTo.ClimbRate = 1D;
		this.spinbuttonPagesTo.Numeric = true;
		this.hbox3.Add(this.spinbuttonPagesTo);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spinbuttonPagesTo]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w24.Position = 5;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.radiobuttonLINQ = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("LINQ"));
		this.radiobuttonLINQ.CanFocus = true;
		this.radiobuttonLINQ.Name = "radiobuttonLINQ";
		this.radiobuttonLINQ.DrawIndicator = true;
		this.radiobuttonLINQ.UseUnderline = true;
		this.radiobuttonLINQ.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.hbox2.Add(this.radiobuttonLINQ);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.radiobuttonLINQ]));
		w25.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.radiobuttonSAX = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("SAX"));
		this.radiobuttonSAX.CanFocus = true;
		this.radiobuttonSAX.Name = "radiobuttonSAX";
		this.radiobuttonSAX.DrawIndicator = true;
		this.radiobuttonSAX.UseUnderline = true;
		this.radiobuttonSAX.Group = this.radiobuttonLINQ.Group;
		this.hbox2.Add(this.radiobuttonSAX);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.radiobuttonSAX]));
		w26.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.radiobuttonDOM = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("DOM"));
		this.radiobuttonDOM.CanFocus = true;
		this.radiobuttonDOM.Name = "radiobuttonDOM";
		this.radiobuttonDOM.DrawIndicator = true;
		this.radiobuttonDOM.UseUnderline = true;
		this.radiobuttonDOM.Group = this.radiobuttonLINQ.Group;
		this.hbox2.Add(this.radiobuttonDOM);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.radiobuttonDOM]));
		w27.Position = 2;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w28.Position = 6;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.buttonSearch = new global::Gtk.Button();
		this.buttonSearch.CanFocus = true;
		this.buttonSearch.Name = "buttonSearch";
		this.buttonSearch.UseUnderline = true;
		this.buttonSearch.Label = global::Mono.Unix.Catalog.GetString("Пошук");
		this.hbox9.Add(this.buttonSearch);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.buttonSearch]));
		w29.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.buttonClear = new global::Gtk.Button();
		this.buttonClear.CanFocus = true;
		this.buttonClear.Name = "buttonClear";
		this.buttonClear.UseUnderline = true;
		this.buttonClear.Label = global::Mono.Unix.Catalog.GetString("Очистити");
		this.hbox9.Add(this.buttonClear);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.buttonClear]));
		w30.Position = 1;
		this.vbox2.Add(this.hbox9);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox9]));
		w31.PackType = ((global::Gtk.PackType)(1));
		w31.Position = 7;
		w31.Expand = false;
		w31.Fill = false;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview = new global::Gtk.TextView();
		this.textview.CanFocus = true;
		this.textview.Name = "textview";
		this.textview.Editable = false;
		this.textview.CursorVisible = false;
		this.GtkScrolledWindow.Add(this.textview);
		this.hbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w34.Position = 1;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w35.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 753;
		this.DefaultHeight = 348;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.HTMLAction.Activated += new global::System.EventHandler(this.BtnConvertActivated);
		this.AboutAuthorAction.Activated += new global::System.EventHandler(this.AboutAuthorActivated);
		this.buttonSearch.Clicked += new global::System.EventHandler(this.OnSearchClicked);
		this.buttonClear.Clicked += new global::System.EventHandler(this.OnClearClicked);
	}
}
